import { Employee } from "./interfaces";

export const mockup: Employee[] = [
  {
    id: 1,
    name: "Alice Smith",
    role: "Software Engineer",
    email: "alice.smith@example.com",
    phone: "050-1234567",
    address: "123 Dizengoff St, Tel Aviv",
  },
  {
    id: 2,
    name: "Bob Johnson",
    role: "Project Manager",
    email: "bob.johnson@example.com",
    phone: "052-9876543",
    address: "456 Ben Yehuda St, Jerusalem",
  },
  {
    id: 3,
    name: "Charlie Brown",
    role: "Data Analyst",
    email: "charlie.brown@example.com",
    phone: "054-5551234",
    address: "789 Herzl St, Haifa",
  },
  {
    id: 4,
    name: "David Lee",
    role: "UX Designer",
    email: "david.lee@example.com",
    phone: "053-1112223",
    address: "101 Allenby St, Tel Aviv",
  },
  {
    id: 5,
    name: "Eve Wilson",
    role: "QA Engineer",
    email: "eve.wilson@example.com",
    phone: "058-4445556",
    address: "202 Jaffa Rd, Jerusalem",
  },
  {
    id: 6,
    name: "Frank Garcia",
    role: "Frontend Developer",
    email: "frank.garcia@example.com",
    phone: "055-7778889",
    address: "303 Horev St, Haifa",
  },
  {
    id: 7,
    name: "Grace Rodriguez",
    role: "Backend Developer",
    email: "grace.rodriguez@example.com",
    phone: "051-3332221",
    address: "404 Rothschild Blvd, Tel Aviv",
  },
  {
    id: 8,
    name: "Henry Martinez",
    role: "DevOps Engineer",
    email: "henry.martinez@example.com",
    phone: "059-6665554",
    address: "505 King George St, Jerusalem",
  },
  {
    id: 9,
    name: "Isabella Anderson",
    role: "Sales Representative",
    email: "isabella.anderson@example.com",
    phone: "056-9998887",
    address: "606 Carmel St, Haifa",
  },
  {
    id: 10,
    name: "Jack Thomas",
    role: "Marketing Specialist",
    email: "jack.thomas@example.com",
    phone: "057-2223334",
    address: "707 Ibn Gabirol St, Tel Aviv",
  },
  {
    id: 11,
    name: "Karen Jackson",
    role: "HR Manager",
    email: "karen.jackson@example.com",
    phone: "050-8889990",
    address: "808 Agrippas St, Jerusalem",
  },
  {
    id: 12,
    name: "Liam White",
    role: "Financial Analyst",
    email: "liam.white@example.com",
    phone: "052-5556667",
    address: "909 Hanasi Blvd, Haifa",
  },
  {
    id: 13,
    name: "Mia Harris",
    role: "Customer Support",
    email: "mia.harris@example.com",
    phone: "054-1118998",
    address: "1010 Sheinkin St, Tel Aviv",
  },
  {
    id: 14,
    name: "Noah Martin",
    role: "IT Specialist",
    email: "noah.martin@example.com",
    phone: "053-4443632",
    address: "1111 Ben Gurion Ave, Jerusalem",
  },
];
